"""
add unique for transaction_id.

Revision ID: af31b31d4a5c
Revises: a664ef335a37
Create Date: 2025-08-21 14:00:22.470011
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af31b31d4a5c"
down_revision: Union[str, Sequence[str], None] = "a664ef335a37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "payments", ["transaction_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "payments", type_="unique")
    # ### end Alembic commands ###
