"""
Добавил created_at, удалил number в acounts.

Revision ID: 4c55b4a8d570
Revises: c3ccd8dcf395
Create Date: 2025-08-19 16:28:30.428461
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c55b4a8d570"
down_revision: Union[str, Sequence[str], None] = "c3ccd8dcf395"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_constraint(op.f("accounts_number_key"), "accounts", type_="unique")
    op.drop_column("accounts", "number")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column("number", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint(
        op.f("accounts_number_key"),
        "accounts",
        ["number"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("accounts", "created_at")
    # ### end Alembic commands ###
